### ISSUE TITLE
[4주차 Question]-양채연

### ISSUE THREAD

**Issue by chaeyeon-yang** [MJU-Developers/23-W-JS-Study#11]
## Question
- eval 함수는 자바스크립트 코드를 나타내는 문자열을 인수로 전달받는다. 전달받은 문자열 코드가 표현식이라면 eval 함수는 문자열 코드를 런타임에 평가하여 값을 생성하고, 전달받은 인수가 표현식이 아닌 문이라면 eval 함수는 문자열 코드를 런타임에 실행한다. (p.329)
- 이 말은 표현식이 아닌문이 호이스팅에 의해 먼저 선언되는 것이 아닌 런타임에 실행된다는 말인가? 표현식인 문과 표현식이 아닌문의 차이점을 설명하고자 하는 것인지 아니면 eval 함수는 표현식이 아닌문을 런타임에 실행한다는 뜻인지 잘 모르겠다.

- const 키워드는 block level scope이고 eval 함수에 의해 런타임에 실행되는데 왜 console.log 결과 값에 반영이 안되는지 궁금하다. let, const  키워드에 strict 모드가 적용되면 어떤 효과가 있는지 잘 모르겠다. (p.331 [예제 21-19])

**Comment by k-kbk** [comment]
2.

> "eval 함수에 전달된 코드는 이미 그 위치에 존재하던 코드처럼 동작한다." (p.330)
> "strict mode(엄격 모드)에서 eval 함수는 기존의 스코프를 수정하지 않고 eval 함수 자신의 자체적인 스코프를 생성한다." (p.330)

var로 선언한 x는 이미 그 위치에 존재하던 코드처럼 foo 함수 스코프에서 동작하고, const로 선언한 x는 strict mode가 적용되어 eval 함수 스코프에서만 동작하기 때문에 foo 함수 스코프(상위 스코프)에는 영향을 주지 않는 것입니다.

**Comment by k-kbk** [comment]
1.

> 표현식은 단일 값을 생성한다.
> 표현식은 값으로 평가될 수 있지만, 표현식이 아닌 문은 값으로 평가될 수 없다.

저자는 단순히 표현식이냐 아니냐(평가냐 실행이냐)를 구분한 것 같습니다.

**Comment by grayashh** [comment]
3. ES6의 let, const 키워드로 선언한 전역 변수는 전역 객체의 프로퍼티가 되지 않고 개념적인 블록 내에 존재하게 됩니다.
let, const 키워드로 선언한 전역 변수는 선언적 환경 레코드에 등록되고 관리됩니다.
let, const 키워드로 선언한 전역 변수는 전역 객체의 프로퍼티가 되지 않고 개념적인 블록 내에 존재하게 된다고 했는데 개념적인 블록이 바로 전역 환경 레코드의 선언적 환경 레코드입니다.
전역 객체의 프로퍼티로서 참조할 수 없고 "선언 단계"와 "초기화 단계"가 분리되어 진행됩니다. 따라서 초기화 단계, 즉 런타임에 실행 흐름이 변수 선언문에 도달하기 전까지 일시적 사각 지대인 TDZ에 빠지게 됩니다.
let, const 키워드로 선언한 변수도 변수 호이스팅이 발생하는 것은 변함이 없습니다, 
단, let, const 키워드로 선언한 변수는 런타임에 컨트롤이 변수 선언문 전까지 일시적 사각 지대 TDZ에 빠지기 때문에 참조할 수 없습니다.
