### ISSUE TITLE
[2주차 Question]-김태강

### ISSUE THREAD

**Issue by grayashh** [MJU-Developers/23-W-JS-Study#6]
## Question
- 프로퍼티 값이 함수일 때 그것을 메서드라고 부르는데 메서드를 콜백함수로 호출하는 등 파라미터로 함수를 넘겼을시 또는 call()메서드를 통해 직접 함수를 호출 했을 때 NaN이 반환되는데 어디까지를 메서드로 지칭해야 맞는 부분일까? (p.130)
- `var person = {'last-name' : 'Lee', 1 : 10};` 이 코드에서 person.last-name을 했을 때 브라우저 콘솔에서는 NaN이 반환되지만 Node.js 환경에서는 name is not defined 에러가 반환된다. 브라우저에는 window 객체에 name 프로퍼티 값이 빈 문자열로 되어 있어 평가가 된다 Node.js는 왜 안되는걸까? (p.132)
- #7

**Comment by MinsuKim21** [comment]
항시 모든값을 반환할수없기때문에 명시적 표현으로 반환한게 아닐까...싶은데..
